[ -f /usr/local/etc/profile.d/autojump.sh ] && . /usr/local/etc/profile.d/autojump.sh
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

. $HOME/.asdf/asdf.sh

. $HOME/.asdf/completions/asdf.bash

export GOPATH=$HOME/code/golang
export GOBIN=$HOME/code/golang/bin
export PATH="$HOME/.cargo/bin:$PATH"
export PATH="/usr/local/opt/icu4c/bin:$PATH"
export PATH="/usr/local/opt/icu4c/sbin:$PATH"
export PATH="$HOME/bin:$PATH"
export PATH="$HOME/usr/local/go/bin:$PATH"
export PATH="$GOBIN:$PATH"
